"""
Django settings for test_project project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'p6+yp$apq_%m^w!ty_2cj)!b#u+xkg%lb-t76q@)1#zt3+)s4s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'mehar2fzr@gmail.com'
EMAIL_HOST_PASSWORD ='roaring40s'
EMAIL_PORT = 587
EMAIL_USE_TLS = True


# Application definition

INSTALLED_APPS = (
    #django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #third party apps
    'crispy_forms',
    'registration',
    #my apps
    'newsletter',
    'polls',
    'eduplus',
    'mentor',
    'feedback',
    'database',
    'social.apps.django_app.default',
    'map',
    'twitter_api'

)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)


AUTHENTICATION_BACKENDS = (
    'social.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
    'social.backends.twitter.TwitterOAuth',
    'django.contrib.auth.backends.ModelBackend'
    )

# SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/profile/'

ROOT_URLCONF = 'test_project.urls'


TEMPLATE_CONTEXT_PROCESSORS = (
   'django.contrib.auth.context_processors.auth',
   'django.core.context_processors.debug',
   'django.core.context_processors.i18n',
   'django.core.context_processors.media',
   'django.core.context_processors.static',
   'django.core.context_processors.tz',
   'django.contrib.messages.context_processors.messages',
   'social.apps.django_app.context_processors.backends',
   'social.apps.django_app.context_processors.login_redirect',
)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'test_project.wsgi.application'
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = "1085955892373-pbg3hal34cie1mqmv775456go4e6jfqk"
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = "-CmPCrXEHfkNGN5NZmSaJ-u3"
SOCIAL_AUTH_TWITTER_KEY = " A5wb6NIlOr8IfMGiqLcuLNJtB"
SOCIAL_AUTH_TWITTER_SECRET = " Vqsl5d58mp92rtW7glW4kBQMFd0YmqGTEoGoy0D9rwkJkZOqH2"


LOGIN_REDIRECT_URL = '/profile/'

#SOCIAL_AUTH_PIPELINE = (
#    'social.pipeline.social_auth.social_details',
#    'social.pipeline.social_auth.social_uid',
#    'social.pipeline.social_auth.auth_allowed',
#    'social.pipeline.social_auth.social_user',
#    'social.pipeline.social_auth.associate_user',
#    'social.pipeline.social_auth.load_extra_data',
#    'social.pipeline.user.user_details',
#)
# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'educamp',
        'USER': 'root',
        'PASSWORD': 'darkknight',
        'HOST':'',
        'PORT':'',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT =  os.path.join(os.path.dirname(BASE_DIR), "static_in_env", 'static_root')



STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static_in_pro", "our_static"),
   # os.path.join(BASE_DIR, "static_in_env"),
   # '/var/www/static/',
)


MEDIA_URL ='/media/'

MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static_in_env", 'media_root')


#registration-redux
ACCOUNT_ACTIVATION_DAYS = 7
REGISTRATION_AUTO_LOGIN = True
SITE_ID = 1
LOGIN_REDIRECT_URL ='/profile/'


#crispy form
CRISPY_TEMPLATE_PACK = 'bootstrap3'
